# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alumnos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alumnos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ralumnos.proto\x12\x07\x61lumnos\"\x07\n\x05Vacio\"m\n\rAlumnoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x12\r\n\x05\x63urso\x18\x05 \x01(\t\x12\x11\n\tdireccion\x18\x06 \x01(\t\"\x90\x01\n\x0e\x41lumnoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x12\r\n\x05\x63urso\x18\x05 \x01(\t\x12\x11\n\tdireccion\x18\x06 \x01(\t\x12\x0f\n\x07mensaje\x18\x07 \x01(\t\x12\x0f\n\x07success\x18\x08 \x01(\x08\"\x1d\n\x0f\x43onsultaRequest\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x0f\x42usquedaRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x61pellido\x18\x02 \x01(\t\x12\r\n\x05\x63urso\x18\x03 \x01(\t2\xa8\x03\n\rAlumnoService\x12\x42\n\x0fRegistrarAlumno\x12\x16.alumnos.AlumnoRequest\x1a\x17.alumnos.AlumnoResponse\x12\x44\n\x0f\x43onsultarAlumno\x12\x18.alumnos.ConsultaRequest\x1a\x17.alumnos.AlumnoResponse\x12\x43\n\x10\x41\x63tualizarAlumno\x12\x16.alumnos.AlumnoRequest\x1a\x17.alumnos.AlumnoResponse\x12\x43\n\x0e\x45liminarAlumno\x12\x18.alumnos.ConsultaRequest\x1a\x17.alumnos.AlumnoResponse\x12I\n\x12\x42uscarPorCriterios\x12\x18.alumnos.BusquedaRequest\x1a\x17.alumnos.AlumnoResponse0\x01\x12\x38\n\x0bListarTodos\x12\x0e.alumnos.Vacio\x1a\x17.alumnos.AlumnoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alumnos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VACIO']._serialized_start=26
  _globals['_VACIO']._serialized_end=33
  _globals['_ALUMNOREQUEST']._serialized_start=35
  _globals['_ALUMNOREQUEST']._serialized_end=144
  _globals['_ALUMNORESPONSE']._serialized_start=147
  _globals['_ALUMNORESPONSE']._serialized_end=291
  _globals['_CONSULTAREQUEST']._serialized_start=293
  _globals['_CONSULTAREQUEST']._serialized_end=322
  _globals['_BUSQUEDAREQUEST']._serialized_start=324
  _globals['_BUSQUEDAREQUEST']._serialized_end=390
  _globals['_ALUMNOSERVICE']._serialized_start=393
  _globals['_ALUMNOSERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
