# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import alumnos_pb2 as alumnos__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in alumnos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlumnoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarAlumno = channel.unary_unary(
                '/alumnos.AlumnoService/RegistrarAlumno',
                request_serializer=alumnos__pb2.AlumnoRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)
        self.ConsultarAlumno = channel.unary_unary(
                '/alumnos.AlumnoService/ConsultarAlumno',
                request_serializer=alumnos__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)
        self.ActualizarAlumno = channel.unary_unary(
                '/alumnos.AlumnoService/ActualizarAlumno',
                request_serializer=alumnos__pb2.AlumnoRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)
        self.EliminarAlumno = channel.unary_unary(
                '/alumnos.AlumnoService/EliminarAlumno',
                request_serializer=alumnos__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)
        self.BuscarPorCriterios = channel.unary_stream(
                '/alumnos.AlumnoService/BuscarPorCriterios',
                request_serializer=alumnos__pb2.BusquedaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)
        self.ListarTodos = channel.unary_stream(
                '/alumnos.AlumnoService/ListarTodos',
                request_serializer=alumnos__pb2.Vacio.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoResponse.FromString,
                _registered_method=True)


class AlumnoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPorCriterios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlumnoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarAlumno,
                    request_deserializer=alumnos__pb2.AlumnoRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
            'ConsultarAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAlumno,
                    request_deserializer=alumnos__pb2.ConsultaRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
            'ActualizarAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarAlumno,
                    request_deserializer=alumnos__pb2.AlumnoRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
            'EliminarAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarAlumno,
                    request_deserializer=alumnos__pb2.ConsultaRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
            'BuscarPorCriterios': grpc.unary_stream_rpc_method_handler(
                    servicer.BuscarPorCriterios,
                    request_deserializer=alumnos__pb2.BusquedaRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
            'ListarTodos': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarTodos,
                    request_deserializer=alumnos__pb2.Vacio.FromString,
                    response_serializer=alumnos__pb2.AlumnoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alumnos.AlumnoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alumnos.AlumnoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlumnoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/RegistrarAlumno',
            alumnos__pb2.AlumnoRequest.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/ConsultarAlumno',
            alumnos__pb2.ConsultaRequest.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/ActualizarAlumno',
            alumnos__pb2.AlumnoRequest.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/EliminarAlumno',
            alumnos__pb2.ConsultaRequest.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPorCriterios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alumnos.AlumnoService/BuscarPorCriterios',
            alumnos__pb2.BusquedaRequest.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alumnos.AlumnoService/ListarTodos',
            alumnos__pb2.Vacio.SerializeToString,
            alumnos__pb2.AlumnoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
